platform: windows

inputs:
  - name: pack-repo

run:
  dir: pack-repo
  path: c:\Go\bin\go.exe
  args:
    - test
    - -mod=vendor
    - -v
    - -count=1
    - -parallel=1
    - github.com/buildpacks/pack
    - github.com/buildpacks/pack/internal/api
    - github.com/buildpacks/pack/internal/archive
    - github.com/buildpacks/pack/internal/blob
    - github.com/buildpacks/pack/internal/build
    - github.com/buildpacks/pack/internal/builder
    - github.com/buildpacks/pack/internal/buildpackage
    - github.com/buildpacks/pack/internal/cache
    - github.com/buildpacks/pack/internal/commands
    - github.com/buildpacks/pack/internal/config
    - github.com/buildpacks/pack/internal/dist
    - github.com/buildpacks/pack/internal/image
    - github.com/buildpacks/pack/internal/logging
    - github.com/buildpacks/pack/internal/paths
    - github.com/buildpacks/pack/internal/stack
