platform: windows
inputs:
  - name: pack-repo

run:
  dir: pack-repo
  path: c:\Go\bin\go.exe
  args:
    - test
    - -mod=vendor
    - -v
    - -count=1
    - -parallel=1
    - github.com/buildpack/pack
    - github.com/buildpack/pack/build
    - github.com/buildpack/pack/builder
    - github.com/buildpack/pack/cache
    - github.com/buildpack/pack/commands
    - github.com/buildpack/pack/config
    - github.com/buildpack/pack/internal/archive
    - github.com/buildpack/pack/logging
