platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.12"

inputs:
  - name: lifecycle-repo
  - name: ci
  - name: version

outputs:
  - name: built-lifecycle

run:
  path: ci/tasks/build-lifecycle/run
