platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.12'


inputs:
  - name: ci
  - name: cnb-template-repo
  - name: golang-image
  - name: lifecycle-version
  - name: pack

run:
  path: ci/tasks/run-cnb-template/run

params:
  CONCOURSE_SERVICE_ACCOUNT_KEY: