jobs:
  - name: build-lifecycle-binaries
    max_in_flight: 1 # prevent accidental reuse of our compound version numbers
    plan:
      - get: lifecycle-repo
        trigger: true
        version: every
      - get: ci
      - get: lifecycle-version
        resource: lifecycle-version
        params:
          pre: alpha
      - put:  lifecycle-build-number
        resource: lifecycle-build-number
        params:
          pre: build
      - task: calculate-lifecycle-version
        file: ci/tasks/calculate-lifecycle-version/task.yml
      - aggregate:
        - task: format-lifecycle
          file: ci/tasks/format-lifecycle/task.yml
        - task: run-unit-tests
          privileged: true
          file: ci/tasks/run-lifecycle-unit/task.yml
        - task: build-binaries
          privileged: true
          file: ci/tasks/build-lifecycle-binaries/task.yml
          input_mapping:
            version: calculated-lifecycle-version
      - aggregate:
        - put: detector-gcs
          params: {file: lifecycle-binaries/detector-*}
        - put: analyzer-gcs
          params: {file: lifecycle-binaries/analyzer-*}
        - put: builder-gcs
          params: {file: lifecycle-binaries/builder-*}
        - put: exporter-gcs
          params: {file: lifecycle-binaries/exporter-*}
        - put: launcher-gcs
          params: {file: lifecycle-binaries/launcher-*}

  - name: build-stack-images
    plan:
      - aggregate:
        ## Get repos, versions
        - get: lifecycle-repo
          version: every
          passed: [build-lifecycle-binaries]
        - get: ci
          passed: [build-lifecycle-binaries]
        - get: lifecycle-version
          resource: lifecycle-version
          passed: [build-lifecycle-binaries]
          params:
            pre: alpha
        - get: lifecycle-build-number
          resource: lifecycle-build-number
          passed: [build-lifecycle-binaries]
          trigger: true

        ## Get binaries
        - get: detector-gcs
          passed: [build-lifecycle-binaries]
        - get: analyzer-gcs
          passed: [build-lifecycle-binaries]
        - get: builder-gcs
          passed: [build-lifecycle-binaries]
        - get: exporter-gcs
          passed: [build-lifecycle-binaries]
        - get: launcher-gcs
          passed: [build-lifecycle-binaries]

      ## Prep
      - aggregate:
        - task: calculate-lifecycle-version
          file: ci/tasks/calculate-lifecycle-version/task.yml
        - task: move-lifecycle-binaries-for-docker
          file: ci/tasks/move-lifecycle-binaries/task.yml
      - task: generate-docker-build-args
        file: ci/tasks/generate-docker-build-args/task.yml
        input_mapping:
          version: calculated-lifecycle-version

      ## Docker builds
      - put: packs-base-image
        params:
          build: lifecycle-binaries
          dockerfile: ci/images/base/Dockerfile
          tag_file: calculated-lifecycle-version/version
          build_args:
            base: "ubuntu:18.04"
      - aggregate:
        - put: packs-run-image
          params:
            build: lifecycle-binaries
            dockerfile: ci/images/run/Dockerfile
            tag_file: calculated-lifecycle-version/version
            build_args_file: docker-build-args/args.json
        - put: packs-build-image
          params:
            build: lifecycle-binaries
            dockerfile: ci/images/build/Dockerfile
            tag_file: calculated-lifecycle-version/version
            build_args:
              go_version: "1.11.4"
            build_args_file: docker-build-args/args.json
      - put: packs-samples-image
        params:
          build: lifecycle-binaries
          dockerfile: ci/images/samples/Dockerfile
          tag_file: calculated-lifecycle-version/version
          build_args_file: docker-build-args/args.json

  - name: pack-unit
    plan:
      - aggregate:
        - get: pack-repo
          resource: pack-repo
          trigger: true
          version: every
        - get: ci
      - task: run-unit-tests
        privileged: true
        file: ci/tasks/run-pack-unit/task.yml

  - name: build-pack
    plan:
    - aggregate:
      - get: pack-repo
        resource: pack-repo
        trigger: true
        version: every
        passed: [pack-unit]
      - get: ci
      - get: pack-version
        resource: pack-version
        params:
          pre: build
    - aggregate:
      - task: build-pack-cli-linux
        file: ci/tasks/build-pack-cli/task.yml
        output_mapping: {pack-release: pack-linux-release}
        params:
          OS_NAME: linux
      - task: build-pack-cli-darwin
        file: ci/tasks/build-pack-cli/task.yml
        output_mapping: {pack-release: pack-darwin-release}
        params:
          OS_NAME: darwin
      - task: build-pack-cli-windows
        file: ci/tasks/build-pack-cli/task.yml
        output_mapping: {pack-release: pack-windows-release}
        params:
          OS_NAME: windows
    - aggregate:
      - put: pack-linux-binary
        params: {file: pack-linux-release/pack-*-linux}
      - put: pack-windows-binary
        params: {file: pack-windows-release/pack-*-windows}
      - put: pack-darwin-binary
        params: {file: pack-darwin-release/pack-*-darwin}

  - name: lifecycle-acceptance
    plan:
      - aggregate:
        - get: pack-linux-binary
          passed: [build-pack]
        - get: ci
          passed: [build-stack-images]
        # Images
        - get: packs-base-image
          passed: [build-stack-images]
        - get: packs-build-image
          passed: [build-stack-images]
          params: {save: true}
        - get: packs-run-image
          passed: [build-stack-images]
          params: {save: true}
        - get: packs-samples-image
          passed: [build-stack-images]
          params: {save: true}
        # Versions
        - get: lifecycle-version
          resource: lifecycle-version
          passed: [build-stack-images]
          params:
            pre: alpha
        - get: lifecycle-build-number
          resource: lifecycle-build-number
          passed: [build-stack-images]
          trigger: true
        # Binaries
        - get: detector-gcs
          passed: [build-stack-images]
        - get: analyzer-gcs
          passed: [build-stack-images]
        - get: builder-gcs
          passed: [build-stack-images]
        - get: exporter-gcs
          passed: [build-stack-images]
        - get: launcher-gcs
          passed: [build-stack-images]
      - task: calculate-lifecycle-version
        file: ci/tasks/calculate-lifecycle-version/task.yml
      - task: acceptance
        privileged: true
        file: ci/tasks/run-acceptance/task.yml
      - task: assemble-binary-archive
        file: ci/tasks/assemble-binary-archive/task.yml
        input_mapping:
          version: calculated-lifecycle-version
      - put: latest-lifecycle-archive-dev
        params:
          file: binaries-archive/lifecycle-binaries-latest.tgz
          content_type: application/gzip # there's no distinct tgz mimetype

  - name: pack-acceptance
    plan:
      - aggregate:
        - get: pack-linux-binary
          passed: [build-pack]
          trigger: true
        - get: ci
          passed: [pack-unit]
        # Images
        - get: packs-base-image
          passed: [build-stack-images]
        - get: packs-build-image
          passed: [build-stack-images]
          params: {save: true}
        - get: packs-run-image
          passed: [build-stack-images]
          params: {save: true}
        - get: packs-samples-image
          passed: [build-stack-images]
          params: {save: true}
        # Binaries
        - get: detector-gcs
          passed: [build-stack-images]
        - get: analyzer-gcs
          passed: [build-stack-images]
        - get: builder-gcs
          passed: [build-stack-images]
        - get: exporter-gcs
          passed: [build-stack-images]
        - get: launcher-gcs
          passed: [build-stack-images]
      - task: acceptance
        privileged: true
        file: ci/tasks/run-acceptance/task.yml

  - name: release-lifecycle
    plan:
      - aggregate:
        - get: ci
          passed: [lifecycle-acceptance]
        - get: lifecycle-version
          resource: lifecycle-version
          passed: [lifecycle-acceptance]
          params:
            pre: alpha
        - get: lifecycle-build-number
          resource: lifecycle-build-number
          passed: [lifecycle-acceptance]
          params:
            pre: build
        - get: packs-base-image
          passed: [lifecycle-acceptance]
          params: {save: true}
        - get: packs-build-image
          passed: [lifecycle-acceptance]
          params: {save: true}
        - get: packs-run-image
          passed: [lifecycle-acceptance]
          params: {save: true}
        - get: packs-samples-image
          passed: [lifecycle-acceptance]
          params: {save: true}

        - get: detector-gcs
          passed: [lifecycle-acceptance]
        - get: analyzer-gcs
          passed: [lifecycle-acceptance]
        - get: builder-gcs
          passed: [lifecycle-acceptance]
        - get: exporter-gcs
          passed: [lifecycle-acceptance]
        - get: launcher-gcs
          passed: [lifecycle-acceptance]


      - task: release-version-create
        file: ci/tasks/release-version-create/task.yml
        # TODO: These images should be published to DockerHub, not GCR, when we're happy with this pipeline
      - task: assemble-binary-archive
        file: ci/tasks/assemble-binary-archive/task.yml
        input_mapping:
          version: lifecycle-version
      - aggregate:
        - put: latest-lifecycle-archive-prod
          params:
            file: binaries-archive/lifecycle-binaries-latest.tgz
            content_type: application/gzip # there's no distinct tgz mimetype
        - put: packs-base-image
          params:
            load: packs-base-image
            tag_file: release-lifecycle-version/version
        - put: packs-build-image
          params:
            load: packs-build-image
            tag_file: release-lifecycle-version/version
        - put: packs-run-image
          params:
            load: packs-run-image
            tag_file: release-lifecycle-version/version
        - put: packs-samples-image
          params:
            load: packs-samples-image
            tag_file: release-lifecycle-version/version
        - put: lifecycle-version
          resource: lifecycle-version
          params:
            pre: alpha

  - name: release-pack
    plan:
    - aggregate:
      - put: pack-version
        resource: pack-version
        params:
          bump: patch
      - get: pack-repo
        passed: [pack-acceptance]
      - get: ci
        passed: [pack-acceptance]
    - task: build-pack-cli-linux
      file: ci/tasks/build-pack-cli/task.yml
      params:
        OS_NAME: linux
    - task: build-pack-cli-darwin
      file: ci/tasks/build-pack-cli/task.yml
      params:
        OS_NAME: darwin
    - task: build-pack-cli-windows
      file: ci/tasks/build-pack-cli/task.yml
      params:
        OS_NAME: windows
    - put: pack-github-release
      params:
        name: pack-release/pack-release-name
        tag: pack-version/version
        tag_prefix: v
        globs:
        - pack-release/pack-*-linux
        - pack-release/pack-*-darwin
        - pack-release/pack-*-windows

