jobs:
  - name: lifecycle-unit
    max_in_flight: 1 # prevent accidental reuse of our compound version numbers
    plan:
      - aggregate:
        - get: lifecycle-repo
          trigger: true
          version: every
        - get: ci
          params:
            submodules: none
        - get: golang-image
          params: {save: true}
      - aggregate:
        - task: format-lifecycle
          image: golang-image
          file: ci/tasks/format-lifecycle/task.yml
        - task: run-unit-tests
          privileged: true
          file: ci/tasks/run-lifecycle-unit/task.yml

  - name: build-lifecycle
    max_in_flight: 1 # prevent accidental reuse of our compound version numbers
    plan:
      - aggregate:
        - get: lifecycle-repo
          passed: [lifecycle-unit]
          trigger: true
        - get: ci
          params:
            submodules: none
        - put: lifecycle-version
          params:
            pre: build
        - get: golang-image
          params: {save: true}
      - task: calculate-lifecycle-version
        file: ci/tasks/calculate-lifecycle-version/task.yml
      - task: build-binaries
        image: golang-image
        file: ci/tasks/build-lifecycle/task.yml
        input_mapping:
          version: calculated-lifecycle-version
      - aggregate:
        - put: lifecycle
          params: {file: lifecycle/lifecycle-*}

  - name: build-stack-images
    plan:
      - aggregate:
        ## Get repos, versions
        - get: lifecycle-repo
          version: every
          passed: [build-lifecycle]
        - get: ci
          params:
            submodules: none
        - get: lifecycle-version
          passed: [build-lifecycle]
          trigger: true

        ## Get binaries
        - get: lifecycle
          passed: [build-lifecycle]

      ## Prep
      - aggregate:
        - task: calculate-lifecycle-version
          file: ci/tasks/calculate-lifecycle-version/task.yml
        - task: move-lifecycle-binaries-for-docker
          file: ci/tasks/move-lifecycle-binaries/task.yml
      - task: generate-docker-build-args
        file: ci/tasks/generate-docker-build-args/task.yml
        input_mapping:
          version: calculated-lifecycle-version

      ## Docker builds
      - aggregate:
        - put: packs-run-image
          params:
            build: ci/images/run
            tag_file: calculated-lifecycle-version/version
            build_args_file: docker-build-args/args.json
        - put: packs-build-image
          params:
            build: ci/images/build
            tag_file: calculated-lifecycle-version/version
            build_args:
              go_version: "1.11.4"
            build_args_file: docker-build-args/args.json

  - name: create-samples-builder
    plan:
    - aggregate:
      - get: pack-linux-binary
        passed: [pack-build]
      - get: samples
      - get: ci
        params:
          submodules: none
      - get: lifecycle-version
        passed: [build-stack-images]
        trigger: true

        ### pass through
      - get: pack-repo
        passed: [pack-build]
      - get: lifecycle
        passed: [build-lifecycle]
      - get: packs-build-image
        passed: [build-stack-images]
        params: {skip_download: true}
      - get: packs-run-image
        passed: [build-stack-images]
        params: {skip_download: true}
      - get: pack-windows-binary
        passed: [pack-build]
      - get: pack-darwin-binary
        passed: [pack-build]
      - get: pack-version
        passed: [pack-build]
        trigger: true

    - task: calculate-lifecycle-version
      file: ci/tasks/calculate-lifecycle-version/task.yml
    - task: create
      file: ci/tasks/create-samples-builder/task.yml
      privileged: true
      input_mapping:
        version: calculated-lifecycle-version
    - put: packs-samples-image
      params:
        load_file: samples-image/image.tar
        load_repository: gcr.io/cncf-buildpacks-ci/packs/samples
        tag_file: calculated-lifecycle-version/version

  - name: pack-unit
    plan:
      - aggregate:
        - get: pack-repo
          resource: pack-repo
          trigger: true
          version: every
        - get: ci
          params:
            submodules: none
        - get: golang-image
          params: {save: true}
      - task: run-unit-tests
        privileged: true
        file: ci/tasks/run-pack-unit/task.yml

  - name: pack-unit-windows
    plan:
      - aggregate:
        - get: pack-repo
          resource: pack-repo
          trigger: true
          version: every
        - get: ci
          params:
            submodules: none
      - task: unit
        file: ci/tasks/run-pack-unit-windows/task.yml
        tags: [windows]

  - name: pack-build
    plan:
    - aggregate:
      - get: pack-repo
        version: every
        passed:
          - pack-unit
          - pack-unit-windows
        trigger: true
      - get: ci
        params:
          submodules: none
      - get: pack-version
        params:
          pre: build
      - get: golang-image
        params: {save: true}
    - aggregate:
      - task: build-pack-cli-linux
        image: golang-image
        file: ci/tasks/build-pack-cli/task.yml
        output_mapping: {pack-release: pack-linux-release}
        params:
          OS_NAME: linux
      - task: build-pack-cli-darwin
        image: golang-image
        file: ci/tasks/build-pack-cli/task.yml
        output_mapping: {pack-release: pack-darwin-release}
        params:
          OS_NAME: darwin
      - task: build-pack-cli-windows
        image: golang-image
        file: ci/tasks/build-pack-cli/task.yml
        output_mapping: {pack-release: pack-windows-release}
        params:
          OS_NAME: windows
    - aggregate:
      - put: pack-linux-binary
        params: {file: pack-linux-release/pack-*-linux}
      - put: pack-windows-binary
        params: {file: pack-windows-release/pack-*-windows}
      - put: pack-darwin-binary
        params: {file: pack-darwin-release/pack-*-darwin}
      - put: pack-version
        params:
          file: pack-version/version

  - name: acceptance
    plan:
      - aggregate:
        # Versions
        - get: pack-version
          passed: [create-samples-builder]
          trigger: true
        - get: lifecycle-version
          passed: [create-samples-builder]
          trigger: true

        # Repos
        - get: pack-repo
          passed: [create-samples-builder]
        - get: ci
          params:
            submodules: none

        # Pack binaries
        - get: pack-linux-binary
          passed: [create-samples-builder]
        - get: pack-windows-binary
          passed: [create-samples-builder]
        - get: pack-darwin-binary
          passed: [create-samples-builder]

        # Lifecycle binaries
        - get: lifecycle
          passed: [create-samples-builder]

        # Images
        - get: packs-build-image
          passed: [create-samples-builder]
          params: {save: true}
        - get: packs-run-image
          passed: [create-samples-builder]
          params: {save: true}
        - get: packs-samples-image
          passed: [create-samples-builder]
          params: {save: true}
        - get: golang-image
          params: {save: true}

      - task: calculate-lifecycle-version
        file: ci/tasks/calculate-lifecycle-version/task.yml
      - task: acceptance
        privileged: true
        file: ci/tasks/run-acceptance/task.yml
      - task: assemble-binary-archive
        file: ci/tasks/assemble-binary-archive/task.yml
        input_mapping:
          version: calculated-lifecycle-version
      - put: latest-lifecycle-archive-dev
        params:
          file: binaries-archive/lifecycle-binaries-latest.tgz
          content_type: application/gzip # there's no distinct tgz mimetype

  - name: release
    plan:
      - aggregate:
        - get: ci
          params:
            submodules: none

        # Versions
        - get: lifecycle-version
          passed: [acceptance]
          params:
            bump: final
        - get: pack-version
          passed: [acceptance]
          params:
            bump: final

        # Binaries
        - get: lifecycle
          passed: [acceptance]

        - get: pack-linux-binary
          passed: [acceptance]
        - get: pack-windows-binary
          passed: [acceptance]
        - get: pack-darwin-binary
          passed: [acceptance]

          # Images
        - get: packs-run-image
          passed: [acceptance]
          params: {save: true}
        - get: packs-build-image
          passed: [acceptance]
          params: {save: true}
        - get: packs-samples-image
          passed: [acceptance]
          params: {save: true}

      - task: calculate-lifecycle-version
        file: ci/tasks/calculate-lifecycle-version/task.yml
      - task: assemble-binary-archive
        file: ci/tasks/assemble-binary-archive/task.yml
        input_mapping:
          version: calculated-lifecycle-version
      - put: latest-lifecycle-archive-prod
        params:
          file: binaries-archive/lifecycle-binaries-latest.tgz
          content_type: application/gzip # there's no distinct tgz mimetype

      ## Create artifacts
      # TODO: These images should be published to DockerHub, not GCR, when we're happy with this pipeline
      - aggregate:
        # Lifecycle
        - put: packs-run-image
          params:
            load: packs-run-image
            tag_file: calculated-lifecycle-version/version
        - put: packs-build-image
          params:
            load: packs-build-image
            tag_file: calculated-lifecycle-version/version
        - do:
          - task: generate-docker-release-args
            file: ci/tasks/generate-docker-release-args/task.yml
            input_mapping:
              version: calculated-lifecycle-version
          - put: packs-samples-image
            params:
              load_base: packs-samples-image
              build: ci/images/samples
              dockerfile: ci/images/samples/Dockerfile.release
              tag_file: calculated-lifecycle-version/version
              build_args_file: docker-release-args/args.json

        # Pack
        - do:
          - aggregate:
            - task: package-pack-release-linux
              file: ci/tasks/package-pack-release/task.yml
              input_mapping:
                pack-binary: pack-linux-binary
              params:
                OS: linux
              output_mapping:
                pack-binary-release: linux-release
            - task: package-pack-release-darwin
              file: ci/tasks/package-pack-release/task.yml
              input_mapping:
                pack-binary: pack-darwin-binary
              params:
                OS: darwin
              output_mapping:
                pack-binary-release: darwin-release
            - task: package-pack-release-windows
              file: ci/tasks/package-pack-release/task.yml
              input_mapping:
                pack-binary: pack-windows-binary
              params:
                OS: windows
              output_mapping:
                pack-binary-release: windows-release
          - put: pack-github-release
            params:
              name: pack-version/version
              tag: pack-version/version
              tag_prefix: v
              globs:
              - linux-release/pack-*-linux.tar.gz
              - darwin-release/pack-*-darwin.tar.gz
              - windows-release/pack-*-windows.zip

      # Bump Versions
      - put: lifecycle-version
        params:
          bump: patch
      - put: pack-version
        params:
          bump: patch
