jobs:
  - name: build-lifecycle-binaries
    plan:
      - get: lifecycle-repo
        trigger: true
        version: every
      - get: ci
      - get: lifecycle-image-version
        params:
          pre: alpha
      - get: lifecycle-build-version
        params:
          pre: build
      - aggregate:
#        - task: format-lifecycle
#          file: ci/tasks/format-lifecycle/task.yml
#        - task: run-unit-tests
#          privileged: true
#          file: ci/tasks/run-lifecycle-unit/task.yml
        - task: build-binaries
          privileged: true
          file: ci/tasks/build-lifecycle-binaries/task.yml
      - aggregate:
        - put: detector-gcs
          params: {file: lifecycle-binaries/detector-*}
        - put: analyzer-gcs
          params: {file: lifecycle-binaries/analyzer-*}
        - put: builder-gcs
          params: {file: lifecycle-binaries/builder-*}
        - put: exporter-gcs
          params: {file: lifecycle-binaries/exporter-*}
        - put: launcher-gcs
          params: {file: lifecycle-binaries/launcher-*}
      - put:  lifecycle-build-version
        params:
          file: lifecycle-build-version/version

  - name: build-stack-images
    plan:

      - aggregate:
        ## Get repos, versions
        - get: lifecycle-repo
          trigger: true
          passed: [build-lifecycle-binaries]
        - get: ci
      #        passed: [build-lifecycle-binaries]
        - get: lifecycle-image-version
          passed: [build-lifecycle-binaries]
          params:
            pre: alpha
        - get: lifecycle-build-version
          passed: [build-lifecycle-binaries]
        ## Get binaries
        - get: detector-gcs
        - get: analyzer-gcs
        - get: builder-gcs
        - get: exporter-gcs
        - get: launcher-gcs

      ## Prep
      - aggregate:
        - task: calculate-lifecycle-version
          file: ci/tasks/calculate-lifecycle-version/task.yml
        - task: move-lifecycle-binaries-for-docker
          file: ci/tasks/move-lifecycle-binaries/task.yml
      - task: generate-docker-build-args
        file: ci/tasks/generate-docker-build-args/task.yml

      ## Docker builds
      - put: packs-base-image
        params:
          build: lifecycle-binaries
          dockerfile: ci/images/base/Dockerfile
          tag_file: built-lifecycle-version/version
          build_args:
            base: "ubuntu:18.04"
      - aggregate:
        - put: packs-run-image
          params:
            build: lifecycle-binaries
            dockerfile: ci/images/run/Dockerfile
            tag_file: built-lifecycle-version/version
            build_args_file: docker-build-args/args.json
        - put: packs-build-image
          params:
            build: lifecycle-binaries
            dockerfile: ci/images/build/Dockerfile
            tag_file: built-lifecycle-version/version
            build_args:
              go_version: "1.11.4"
            build_args_file: docker-build-args/args.json
      - put: packs-samples-image
        params:
          build: lifecycle-binaries
          dockerfile: ci/images/samples/Dockerfile
          tag_file: built-lifecycle-version/version
          build_args_file: docker-build-args/args.json

  - name: pack-unit
    plan:
      - aggregate:
        - get: pack-repo
          resource: pack-repo
          trigger: true
          version: every
        - get: ci
      - task: run-unit-tests
        privileged: true
        file: ci/tasks/run-pack-unit/task.yml

  - name: acceptance
    plan:
      - aggregate:
        - get: pack-repo
          resource: pack-repo
          passed: [pack-unit]
        - get: ci
          passed: [build-stack-images]
        - get: packs-build-image
          passed: [build-stack-images]
          params: {save: true}
        - get: packs-run-image
          passed: [build-stack-images]
          params: {save: true}
        - get: packs-samples-image
          passed: [build-stack-images]
          trigger: true
          params: {save: true}
        - get: lifecycle-image-version
          passed: [build-stack-images]
        - get: lifecycle-build-version
          passed: [build-stack-images]
      - task: acceptance
        privileged: true
        file: ci/tasks/run-acceptance/task.yml
      - put: lifecycle-build-version
#        params:
#          pre: build

  - name: release-lifecycle
    plan:
      - aggregate:
        - get: ci
          passed: [acceptance]
        - get: lifecycle-image-version
          passed: [acceptance]
          params:
            pre: alpha
        - get: lifecycle-build-version
          passed: [acceptance]
          params:
            pre: build
        - get: packs-build-image
          passed: [acceptance]
          params: {save: true}
        - get: packs-run-image
          passed: [acceptance]
          params: {save: true}
        - get: packs-samples-image
          passed: [acceptance]
          params: {save: true}
      - task: release-version-create
        file: ci/tasks/release-version-create/task.yml
      - aggregate:
        - put: packs-build-image
          params:
            load: packs-build-image
            tag_file: release-lifecycle-version/version
        - put: packs-run-image
          params:
            load: packs-run-image
            tag_file: release-lifecycle-version/version
        - put: packs-samples-image
          params:
            load: packs-samples-image
            tag_file: release-lifecycle-version/version
        - put: packs-run-image
          params:
            load: packs-run-image
            tag_file: release-lifecycle-version/version
        - put: lifecycle-image-version
          params:
            pre: alpha

  - name: release-pack
    plan:
    - put: pack-version
      params:
        bump: patch
    - aggregate:
      - get: lifecycle-image-version
        passed: [release-lifecycle]
      - get: pack-repo
        passed: [acceptance]
      - get: ci
    - task: build-pack-cli-linux
      file: ci/tasks/build-pack-cli/task.yml
      params:
        OS_NAME: linux
    - put: pack-github-release
      params:
        name: pack-release/pack-release-path
        tag: pack-version/version
        tag_prefix: v
        commitish: pack-repo/.git/ref
        globs:
        - pack-release/pack-*


    # rebuild
    # put binaries in bucket
    # put github release

