jobs:
  - name: lifecycle-unit
    max_in_flight: 1 # prevent accidental reuse of our compound version numbers
    plan:
      - get: lifecycle-repo
        trigger: true
        version: every
      - get: ci
      - aggregate:
        - task: format-lifecycle
          file: ci/tasks/format-lifecycle/task.yml
        - task: run-unit-tests
          privileged: true
          file: ci/tasks/run-lifecycle-unit/task.yml

  - name: lifecycle-unit
    max_in_flight: 1 # prevent accidental reuse of our compound version numbers
    plan:
      - get: lifecycle-repo
        trigger: true
        version: every
      - get: ci
      - aggregate:
        - task: format-lifecycle
          file: ci/tasks/format-lifecycle/task.yml
        - task: run-unit-tests
          privileged: true
          file: ci/tasks/run-lifecycle-unit/task.yml

  - name: build-lifecycle-binaries
    max_in_flight: 1 # prevent accidental reuse of our compound version numbers
    plan:
      - aggregate:
        - get: lifecycle-repo
          passed: [lifecycle-unit]
          trigger: true
        - get: ci
        - put: lifecycle-version
          params:
            pre: build
      - task: calculate-lifecycle-version
        file: ci/tasks/calculate-lifecycle-version/task.yml
      - task: build-binaries
        privileged: true
        file: ci/tasks/build-lifecycle-binaries/task.yml
        input_mapping:
          version: calculated-lifecycle-version
      - aggregate:
        - put: detector-gcs
          params: {file: lifecycle-binaries/detector-*}
        - put: restorer-gcs
          params: {file: lifecycle-binaries/restorer-*}
        - put: analyzer-gcs
          params: {file: lifecycle-binaries/analyzer-*}
        - put: builder-gcs
          params: {file: lifecycle-binaries/builder-*}
        - put: exporter-gcs
          params: {file: lifecycle-binaries/exporter-*}
        - put: cacher-gcs
          params: {file: lifecycle-binaries/cacher-*}
        - put: launcher-gcs
          params: {file: lifecycle-binaries/launcher-*}

  - name: build-stack-images
    plan:
      - aggregate:
        ## Get repos, versions
        - get: lifecycle-repo
          version: every
          passed: [build-lifecycle-binaries]
        - get: ci
        - get: lifecycle-version
          passed: [build-lifecycle-binaries]
          trigger: true

        ## Get binaries
        - get: detector-gcs
          passed: [build-lifecycle-binaries]
        - get: restorer-gcs
          passed: [build-lifecycle-binaries]
        - get: analyzer-gcs
          passed: [build-lifecycle-binaries]
        - get: builder-gcs
          passed: [build-lifecycle-binaries]
        - get: exporter-gcs
          passed: [build-lifecycle-binaries]
        - get: cacher-gcs
          passed: [build-lifecycle-binaries]
        - get: launcher-gcs
          passed: [build-lifecycle-binaries]

      ## Prep
      - aggregate:
        - task: calculate-lifecycle-version
          file: ci/tasks/calculate-lifecycle-version/task.yml
        - task: move-lifecycle-binaries-for-docker
          file: ci/tasks/move-lifecycle-binaries/task.yml
      - task: generate-docker-build-args
        file: ci/tasks/generate-docker-build-args/task.yml
        input_mapping:
          version: calculated-lifecycle-version

      ## Docker builds
      - put: packs-base-image
        params:
          build: lifecycle-binaries
          dockerfile: ci/images/base/Dockerfile
          tag_file: calculated-lifecycle-version/version
          build_args:
            base: "ubuntu:18.04"
      - aggregate:
        - put: packs-run-image
          params:
            build: ci/images/run
            tag_file: calculated-lifecycle-version/version
            build_args_file: docker-build-args/args.json
        - do:
          - put: packs-build-image
            params:
              build: ci/images/build
              tag_file: calculated-lifecycle-version/version
              build_args:
                go_version: "1.11.4"
              build_args_file: docker-build-args/args.json
          - put: packs-samples-image
            params:
              build: ci/images/samples
              tag_file: calculated-lifecycle-version/version
              build_args_file: docker-build-args/args.json

  - name: pack-unit
    plan:
      - aggregate:
        - put: pack-version
          params:
            pre: build
        - get: pack-repo
          resource: pack-repo
          trigger: true
          version: every
        - get: ci
      - task: run-unit-tests
        privileged: true
        file: ci/tasks/run-pack-unit/task.yml

  - name: pack-unit-experimental
    plan:
      - aggregate:
        - put: pack-version
          params:
            pre: build
        - get: pack-repo
          resource: pack-repo
          trigger: true
          version: every
        - get: ci-experimental
      - task: run-unit-tests
        privileged: true
        file: ci/tasks/run-pack-unit/task.yml

  - name: pack-build
    plan:
    - aggregate:
      - get: pack-repo
        version: every
        passed: [pack-unit]
      - get: ci
      - get: pack-version
        trigger: true
        passed: [pack-unit]
    - aggregate:
      - task: build-pack-cli-linux
        file: ci/tasks/build-pack-cli/task.yml
        output_mapping: {pack-release: pack-linux-release}
        params:
          OS_NAME: linux
      - task: build-pack-cli-darwin
        file: ci/tasks/build-pack-cli/task.yml
        output_mapping: {pack-release: pack-darwin-release}
        params:
          OS_NAME: darwin
      - task: build-pack-cli-windows
        file: ci/tasks/build-pack-cli/task.yml
        output_mapping: {pack-release: pack-windows-release}
        params:
          OS_NAME: windows
    - aggregate:
      - put: pack-linux-binary
        params: {file: pack-linux-release/pack-*-linux}
      - put: pack-windows-binary
        params: {file: pack-windows-release/pack-*-windows}
      - put: pack-darwin-binary
        params: {file: pack-darwin-release/pack-*-darwin}

  - name: acceptance
    plan:
      - aggregate:
        # Versions
        - get: pack-version
          passed: [pack-build]
          trigger: true
        - get: lifecycle-version
          passed: [build-stack-images]
          trigger: true

        # Repos
        - get: pack-repo
          passed: [pack-build]
        - get: ci

        # Pack binaries
        - get: pack-linux-binary
          passed: [pack-build]
        - get: pack-windows-binary
          passed: [pack-build]
        - get: pack-darwin-binary
          passed: [pack-build]

        # Lifecycle binaries
        - get: detector-gcs
          passed: [build-stack-images]
        - get: restorer-gcs
          passed: [build-stack-images]
        - get: analyzer-gcs
          passed: [build-stack-images]
        - get: builder-gcs
          passed: [build-stack-images]
        - get: exporter-gcs
          passed: [build-stack-images]
        - get: cacher-gcs
          passed: [build-stack-images]
        - get: launcher-gcs
          passed: [build-stack-images]

        # Images
        - get: packs-base-image
          passed: [build-stack-images]
          params:
             skip_download: true
        - get: packs-build-image
          passed: [build-stack-images]
          params: {save: true}
        - get: packs-run-image
          passed: [build-stack-images]
          params: {save: true}
        - get: packs-samples-image
          passed: [build-stack-images]
          params: {save: true}

      - task: calculate-lifecycle-version
        file: ci/tasks/calculate-lifecycle-version/task.yml
      - task: acceptance
        privileged: true
        file: ci/tasks/run-acceptance/task.yml
      - task: assemble-binary-archive
        file: ci/tasks/assemble-binary-archive/task.yml
        input_mapping:
          version: calculated-lifecycle-version
      - put: latest-lifecycle-archive-dev
        params:
          file: binaries-archive/lifecycle-binaries-latest.tgz
          content_type: application/gzip # there's no distinct tgz mimetype

  - name: release
    plan:
      - aggregate:
        - get: ci

        # Versions
        - get: lifecycle-version
          passed: [acceptance]
          params:
            bump: final
        - get: pack-version
          passed: [acceptance]
          params:
            bump: final

        # Binaries
        - get: detector-gcs
          passed: [acceptance]
        - get: restorer-gcs
          passed: [acceptance]
        - get: analyzer-gcs
          passed: [acceptance]
        - get: builder-gcs
          passed: [acceptance]
        - get: exporter-gcs
          passed: [acceptance]
        - get: cacher-gcs
          passed: [acceptance]
        - get: launcher-gcs
          passed: [acceptance]

        - get: pack-linux-binary
          passed: [acceptance]
        - get: pack-windows-binary
          passed: [acceptance]
        - get: pack-darwin-binary
          passed: [acceptance]

          # Images
        - get: packs-base-image
          passed: [acceptance]
          params:
            save: true
        - get: packs-run-image
          passed: [acceptance]
          params:
            save: true
        - get: packs-build-image
          passed: [acceptance]
          params:
            save: true
        - get: packs-samples-image
          passed: [acceptance]
          params:
            save: true

      - task: calculate-lifecycle-version
        file: ci/tasks/calculate-lifecycle-version/task.yml
      - task: assemble-binary-archive
        file: ci/tasks/assemble-binary-archive/task.yml
        input_mapping:
          version: calculated-lifecycle-version
      - put: latest-lifecycle-archive-prod
        params:
          file: binaries-archive/lifecycle-binaries-latest.tgz
          content_type: application/gzip # there's no distinct tgz mimetype

      ## Create artifacts
      # TODO: These images should be published to DockerHub, not GCR, when we're happy with this pipeline
      - aggregate:
        # Lifecycle
        - put: packs-base-image
          params:
            load: packs-base-image
            tag_file: calculated-lifecycle-version/version
        - put: packs-run-image
          params:
            load: packs-run-image
            tag_file: calculated-lifecycle-version/version
        - put: packs-build-image
          params:
            load: packs-build-image
            tag_file: calculated-lifecycle-version/version
        - do:
          - task: generate-docker-release-args
            file: ci/tasks/generate-docker-release-args/task.yml
            input_mapping:
              version: calculated-lifecycle-version
          - put: packs-samples-image
            params:
              load_base: packs-samples-image
              build: ci/images/samples
              dockerfile: ci/images/samples/Dockerfile.release
              tag_file: calculated-lifecycle-version/version
              build_args_file: docker-release-args/args.json

        # Pack
        - do:
          - aggregate:
            - task: package-pack-release-linux
              file: ci/tasks/package-pack-release/task.yml
              input_mapping:
                pack-binary: pack-linux-binary
              params:
                OS: linux
              output_mapping:
                pack-binary-release: linux-release
            - task: package-pack-release-darwin
              file: ci/tasks/package-pack-release/task.yml
              input_mapping:
                pack-binary: pack-darwin-binary
              params:
                OS: darwin
              output_mapping:
                pack-binary-release: darwin-release
            - task: package-pack-release-windows
              file: ci/tasks/package-pack-release/task.yml
              input_mapping:
                pack-binary: pack-windows-binary
              params:
                OS: windows
              output_mapping:
                pack-binary-release: windows-release
          - put: pack-github-release
            params:
              name: pack-version/version
              tag: pack-version/version
              tag_prefix: v
              globs:
              - linux-release/pack-*-linux.tar.gz
              - darwin-release/pack-*-darwin.tar.gz
              - windows-release/pack-*-windows.zip

      # Bump Versions
      - put: lifecycle-version
        params:
          bump: patch
      - put: pack-version
        params:
          bump: patch
