platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/docker-image-resource

inputs:
- name: ci
- name: pack-version
- name: pack-binary

params:
- OS:

outputs:
- name: pack-binary-release

run:
  path: ci/tasks/package-pack-release/run
