platform: linux
image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: bionic

inputs:
- name: ci
- name: version
- name: pack-binary

params:
- OS:

outputs:
- name: pack-binary-release

run:
  path: ci/tasks/package-pack-release/run
