platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/docker-image-resource

inputs:
  - name: lifecycle-repo
  - name: ci
  - name: golang-image

run:
  path: ci/tasks/run-lifecycle-unit/run