jobs:
  - name: build-bionic-stack
    plan:
      - aggregate:
        ## Get repos, versions
        - get: stacks-repo
          trigger: true
        - get: ci
          params:
            submodules: none
        - get: bionic-stack-version
          params:
            pre: rc

      ## Prep
      - task: generate-docker-build-args
        file: ci/tasks/generate-docker-build-args/task.yml
        input_mapping:
          version: bionic-stack-version

      ## Docker builds
      - put: bionic-base-image
        params:
          build: stacks-repo/bionic/base
          tag_file: bionic-stack-version/version
          tag_as_latest: true
      - aggregate:
        - put: bionic-run-image
          params:
            build: stacks-repo/bionic/run
            tag_file: bionic-stack-version/version
            build_args_file: docker-build-args/args.json
            tag_as_latest: true
        - put: bionic-build-image
          params:
            build: stacks-repo/bionic/build
            tag_file: bionic-stack-version/version
            tag_as_latest: true
            build_args_file: docker-build-args/args.json
            build_args:
              go_version: "1.12"
      - put: bionic-stack-version
        params:
          file: bionic-stack-version/version
