jobs:
  - name: lifecycle-unit
    max_in_flight: 1 # prevent accidental reuse of our compound version numbers
    plan:
      - aggregate:
        # Repos
        - get: lifecycle-repo
          trigger: true
          version: every
        - get: ci
          params:
            submodules: none

        # Images
        - get: golang-image
          params: {save: true}

      - task: run-unit-tests
        privileged: true
        file: ci/tasks/run-lifecycle-unit/task.yml

  - name: lifecycle-build
    max_in_flight: 1 # prevent accidental reuse of our compound version numbers
    plan:
      - aggregate:
        # Repos
        - get: lifecycle-repo
          passed: [lifecycle-unit]
          trigger: true
        - get: ci
          params:
            submodules: none

        # Versions
        - get: lifecycle-version
          params:
            pre: build

        # Images
        - get: golang-image
          params: {save: true}

      - task: build-binaries
        image: golang-image
        file: ci/tasks/build-lifecycle/task.yml
        input_mapping:
          version: lifecycle-version
      - put: lifecycle
        params: {file: built-lifecycle/lifecycle-*}
      - put: lifecycle-version
        params:
          file: lifecycle-version/version

  - name: lifecycle-release
    plan:
      - aggregate:
        # Repos
        - get: ci
          params:
            submodules: none
        - get: lifecycle
          passed: [lifecycle-build]
        - get: lifecycle-repo
          passed: [lifecycle-build]
          
        # Versions
        - get: lifecycle-version
          params:
            bump: final
          
      - task: prepare-release
        file: ci/tasks/prepare-lifecycle-release/task.yml
      - put: lifecycle-github-release
        params:
          name: release-artifacts/name
          tag: release-artifacts/tag
          commitish: release-artifacts/commit-sha
          globs: [release-artifacts/*.tgz]
      - put: lifecycle-version
        params:
          bump: minor
