platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.12"

inputs:
  - name: lifecycle-repo
  - name: ci

outputs:
  - name: lifecycle-binaries

run:
  path: ci/tasks/format-lifecycle/run
