platform: linux
image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: bionic

inputs:
- name: ci
- name: lifecycle

outputs:
- name: lifecycle-binaries

run:
  path: ci/tasks/move-lifecycle-binaries/run
