platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.11"

inputs:
  - name: lifecycle-repo
  - name: ci
  - name: lifecycle-version
  - name: lifecycle-build-number

outputs:
  - name: lifecycle-binaries

run:
  path: ci/tasks/build-lifecycle-binaries/run
