jobs:
  - name: build-ci-image
    plan:
      - get: ci-dockerfile
        trigger: true
        params:
          submodules: none
      
      - put: ci-image
        params:
          build: ci-dockerfile/images/ci
        