platform: linux
image_resource:
  type: docker-image
  source:
    repository: alpine/git

inputs:
  - name: ci
  - name: tap
  - name: pack-version
  - name: release-artifacts

outputs:
  - name: updated-tap

run:
  path: ci/tasks/update-pack-brew-formula/run
  
params:
  GITHUB_EMAIL: