platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/docker-image-resource
    tag: 1.3.0

inputs:
  - name: pack-repo
  - name: ci
  - name: golang-image

run:
  path: ci/tasks/run-pack-unit/run