platform: linux
image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: bionic

inputs:
  - name: ci
  - name: version
  - name: packs-samples-image

outputs:
  - name: docker-release-args

run:
  path: ci/tasks/generate-docker-release-args/run
