jobs:

  - name: update-homebrew
    plan:
    - in_parallel:
      # Repos
      - get: ci
        params:
          submodules: none
      - get: tap

      # Github Releases
      - get: released-pack
        trigger: true
        params:
          globs: [pack-*-macos.tgz]

    - task: update-homebrew
      file: ci/tasks/update-pack-brew-formula/task.yml
      params:
        GITHUB_EMAIL: ((buildpack-robot-github-email))
    - put: tap
      params:
        repository: updated-tap