jobs:
  - name: pack-unit
    plan:
      - aggregate:
        - get: pack-repo
          resource: pack-repo
          trigger: true
          version: every
        - get: ci
          params:
            submodules: none
        - get: golang-image
          params: {save: true}
      - task: run-unit-tests
        privileged: true
        file: ci/tasks/run-pack-unit/task.yml

  - name: pack-unit-windows
    plan:
      - aggregate:
        - get: pack-repo
          resource: pack-repo
          trigger: true
          version: every
        - get: ci
          params:
            submodules: none
      - task: unit
        file: ci/tasks/run-pack-unit-windows/task.yml
        tags: [windows]

  - name: pack-build
    plan:
    - aggregate:
      - get: pack-repo
        version: every
        passed:
          - pack-unit
          - pack-unit-windows
        trigger: true
      - get: ci
        params:
          submodules: none
      - get: pack-version
        params:
          pre: build
      - get: golang-image
        params: {save: true}
    - aggregate:
      - task: build-pack-cli-linux
        image: golang-image
        file: ci/tasks/build-pack-cli/task.yml
        output_mapping: {pack-release: pack-linux-release}
        params:
          OS_NAME: linux
      - task: build-pack-cli-darwin
        image: golang-image
        file: ci/tasks/build-pack-cli/task.yml
        output_mapping: {pack-release: pack-darwin-release}
        params:
          OS_NAME: darwin
      - task: build-pack-cli-windows
        image: golang-image
        file: ci/tasks/build-pack-cli/task.yml
        output_mapping: {pack-release: pack-windows-release}
        params:
          OS_NAME: windows
    - aggregate:
      - put: pack-linux-binary
        params: {file: pack-linux-release/pack-*-linux}
      - put: pack-windows-binary
        params: {file: pack-windows-release/pack-*-windows}
      - put: pack-darwin-binary
        params: {file: pack-darwin-release/pack-*-darwin}
      - put: pack-version
        params:
          file: pack-version/version

  - name: acceptance-lifecycle-master
    plan:
      - aggregate:
        # Versions
        - get: pack-version
          passed: [pack-build]
          trigger: true
        - get: lifecycle-version
          trigger: true

        # Repos
        - get: pack-repo
          passed: [pack-build]
        - get: ci
          params:
            submodules: none

        # Pack binaries
        - get: pack-linux-binary
          passed: [pack-build]
        - get: pack-windows-binary
          passed: [pack-build]
        - get: pack-darwin-binary
          passed: [pack-build]

        # Lifecycle binaries
        - get: lifecycle

        # Images
        - get: golang-image
          params: {save: true}

      - task: acceptance
        privileged: true
        file: ci/tasks/run-acceptance/task.yml

  - name: acceptance-default-lifecycle
    plan:
      - aggregate:
        # Versions
        - get: pack-version
          passed: [pack-build]
          trigger: true

        # Repos
        - get: pack-repo
          passed: [pack-build]
        - get: ci
          params:
            submodules: none

        # Pack binaries
        - get: pack-linux-binary
          passed: [pack-build]
        - get: pack-windows-binary
          passed: [pack-build]
        - get: pack-darwin-binary
          passed: [pack-build]

        # Images
        - get: golang-image
          params: {save: true}

      - task: acceptance
        privileged: true
        file: ci/tasks/run-acceptance/task.yml
        params:
          SELECT_LIFECYCLE: default

  - name: acceptance-lifecycle-N-1
    plan:
      - aggregate:
          # Versions
          - get: pack-version
            passed: [pack-build]
            trigger: true

          # Repos
          - get: pack-repo
            passed: [pack-build]
          - get: ci
            params:
              submodules: none

          # Pack binaries
          - get: pack-linux-binary
            passed: [pack-build]
          - get: pack-windows-binary
            passed: [pack-build]
          - get: pack-darwin-binary
            passed: [pack-build]

          # Images
          - get: golang-image
            params: {save: true}

      - task: acceptance
        privileged: true
        file: ci/tasks/run-acceptance/task.yml
        params:
          SELECT_LIFECYCLE: previous

  - name: pack-release-TESTING-ONLY
    plan:
      - aggregate:

          # Repos
          - get: ci
            params:
              submodules: none
          - get: pack-repo
            passed: [acceptance-lifecycle-master, acceptance-default-lifecycle, acceptance-lifecycle-N-1]
          - get: tap

          # Binaries
          - get: pack-windows-binary
            passed: [acceptance-lifecycle-master, acceptance-default-lifecycle, acceptance-lifecycle-N-1]
          - get: pack-darwin-binary
            passed: [acceptance-lifecycle-master, acceptance-default-lifecycle, acceptance-lifecycle-N-1]
          - get: pack-linux-binary
            passed: [acceptance-lifecycle-master, acceptance-default-lifecycle, acceptance-lifecycle-N-1]

          # Versions
          - get: pack-version
            params:
              bump: final

      - task: prepare-release
        file: ci/tasks/prepare-pack-release/task.yml
      - task: update-homebrew
        file: ci/tasks/update-pack-brew-formula/task.yml
        params:
          GITHUB_EMAIL: ((buildpack-robot-github-email))
      - put: pack-github-release
        params:
          name: release-artifacts/name
          tag: release-artifacts/tag
          commitish: release-artifacts/commit-sha
          globs: [release-artifacts/*.tgz, release-artifacts/*.zip]
      - put: tap
        params:
          repository: updated-tap
      - put: pack-version
        params:
          bump: minor