platform: windows

inputs:
  - name: pack-repo

params:
  COMPILE_PACK_WITH_VERSION: 0.0.0

run:
  dir: pack-repo
  path: c:\Go\bin\go.exe
  args:
    - test
    - -mod=vendor
    - -v
    - -count=1
    - -parallel=1
    - -tags=acceptance
    - github.com/buildpacks/pack/acceptance