platform: windows

inputs:
  - name: ci
  - name: golang-image
  - name: pack-repo
  - name: pack-windows-binary
  - name: lifecycle-repo
    optional: true
  - name: lifecycle
    optional: true
  - name: lifecycle-version
    optional: true

run:
  dir: pack-repo
  path: c:\Go\bin\go.exe
  args:
    - test
    - -mod=vendor
    - -v
    - -count=1
    - -parallel=1
    - -tags=acceptance
    - github.com/buildpack/pack/acceptance