---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
  - name: bosh-deployment

outputs:
  - name: bosh-deployment-output

run:
  path: bosh-deployment/ci/tasks/consolidate-versions.sh
