platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/docker-image-resource

inputs:
  - name: lifecycle-repo
  - name: ci

outputs:
  - name: built-lifecycle-images

run:
  path: ci/tasks/stack-images/run
