platform: linux
image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: bionic

inputs:
- name: ci
- name: lifecycle-image-version
- name: lifecycle-build-version

outputs:
- name: built-lifecycle-version

run:
  path: ci/tasks/calculate-lifecycle-version/run
