platform: linux
image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: bionic

inputs:
- name: ci
- name: lifecycle-version
- name: lifecycle-build-number

outputs:
- name: calculated-lifecycle-version

run:
  path: ci/tasks/calculate-lifecycle-version/run
