platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/docker-image-resource

inputs:
  - name: ci
  - name: golang-image
  - name: pack-repo
  - name: pack-linux-binary
  - name: lifecycle-repo
    optional: true
  - name: lifecycle
    optional: true
  - name: lifecycle-version
    optional: true

run:
  path: ci/tasks/run-acceptance/run

params:
  SELECT_LIFECYCLE:
