platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang/1.12

inputs:
  - name: pack-repo
  - name: pack-linux-binary
  - name: lifecycle
    optional: true
  - name: ci
  - name: golang-image

run:
  path: ci/tasks/run-acceptance/run

params:
  USE_DEFAULT_LIFECYCLE:
