platform: linux
image_resource:
  type: docker-image
  source:
    repository: concourse/docker-image-resource

inputs:
  - name: pack-repo
  - name: pack-linux-binary
  - name: lifecycle
    optional: true
  - name: ci
  - name: golang-image
  - name: lifecycle-version

run:
  path: ci/tasks/run-acceptance/run

params:
  USE_DEFAULT_LIFECYCLE:
