platform: linux
image_resource:
  type: docker-image
  source:
    repository: cnbs/ci

inputs:
  - name: ci
  - name: pack-repo
  - name: pack
  - name: previous-pack
    optional: true
  - name: lifecycle
    optional: true
  - name: pack-version
    optional: true
    
run:
  path: ci/tasks/run-acceptance/run

params:
  ACCEPTANCE_SUITE_CONFIG: